### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "sabrina",
    "email": "sabrina@gmail.com",
    "password": "password123",
    "identity_type": "Owner Binar",
    "identity_number": "123456789",
    "address": "Jalan Menuju Surga"
}

### login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "sabrina@gmail.com",
    "password": "password123"
}

### login token
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsIm5hbWUiOiJzYWJyaW5hIiwiZW1haWwiOiJzYWJyaW5hQGdtYWlsLmNvbSIsImlhdCI6MTcxMzU0NDA0OX0.5_Sa7YkvTxmAKOAtBW7qQn502QkHhBJzglWe_8ndVrY