### Create Transaction
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "amount": 300000,
    "source_account_id": 83,
    "destination_account_id": 83
}

### Get all Transaction
GET http://localhost:3000/api/v1/transactions

### Get Detail Transaction by id
GET http://localhost:3000/api/v1/transactions/66

### Delete Transaction user by id
Delete http://localhost:3000/api/v1/transactions/53